language: haxe

haxe:
  - 3.4.4
  - stable
  - 4.0.0-preview.4
  - development

matrix:
  allow_failures:
    - haxe: development

install:
  - haxelib install munit
  - haxelib install hxnodejs
  - haxelib git tink_hxx git@github.com:kLabz/tink_anon.git
  - haxelib git tink_anon git@github.com:haxetink/tink_anon.git

script:
  - haxelib run munit test -js

# deploy:
#   - provider: script
#     haxe: 3.4.4
#     script: bash ./releaseHaxelib.sh $HAXELIB_USER $HAXELIB_PWD
#     on:
#       tags: true
