name: Tests

on: [push, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        haxe: [4.3.6, latest]

    steps:
    - uses: actions/checkout@v1

    - name: Setup haxe ${{ matrix.haxe }}
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: ${{ matrix.haxe }}

    - name: Install libs
      run: |
        git config --global url."https://github.com/".insteadOf "git@github.com:"
        haxelib newrepo
        haxelib install munit
        haxelib install hxnodejs
        haxelib git tink_hxx git@github.com:kLabz/tink_hxx.git
        haxelib git tink_anon git@github.com:haxetink/tink_anon.git

    - name: Run tests
      run: |
        haxelib run munit test -js

